#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop aesdsocket daemon
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_NAME=aesdsocket
PIDFILE=/var/run/$DAEMON_NAME.pid

case "$1" in
    start)
        echo "Starting $DAEMON_NAME..."
        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- -d
        echo "$DAEMON_NAME started."
        ;;
    stop)
        echo "Stopping $DAEMON_NAME..."
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        echo "$DAEMON_NAME stopped."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        if [ -e $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            if ps -p $PID > /dev/null 2>&1; then
                echo "$DAEMON_NAME is running with PID $PID."
                exit 0
            else
                echo "$DAEMON_NAME is not running, but pid file exists."
                exit 1
            fi
        else
            echo "$DAEMON_NAME is not running."
            exit 3
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
